# ecoinvent import

## 1. Setup background

In [1]:
# basic imports from brightway
import bw2analyzer as ba
import bw2calc as bc
import bw2data as bd
import bw2io as bi
import bw2analyzer as bwa
from bw2data import methods
from bw2io import create_default_biosphere3
from bw2io import SingleOutputEcospold2Importer
from bw2io.importers import Ecospold2BiosphereImporter

# other relevant packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from functions.utils import Config

c:\Users\SimonVemmelund\Documents\Python\brightway_project_template\.venv\Lib\site-packages\bw2calc\__init__.py:59: UserWarning: No fast sparse solver found
  warnings.warn("No fast sparse solver found")

15:40:44+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.

In [ ]:
bd.projects.set_current(Config.PROJECT_NAME)

print(f"Current Brightway project: {bd.projects.current}")

## 2. Option A: install ecoinvent with username and password

Note that there are different ways of importing ecoinvent to your brightway project. If you have username and password at hand you can install the database just using this access codes. The first suggestion is to use a structured importer available from brightway.

In [3]:
bi.import_ecoinvent_release(
    version = Config.ECOINVENT_VERSION,
    system_model = Config.ECOINVENT_SYSTEM_MODEL,
    username = Config.ECOINVENT_USERNAME,
    password = Config.ECOINVENT_PASSWORD
    )

Applying strategy: normalize_units
Applying strategy: drop_unspecified_subcategories
Applying strategy: ensure_categories_are_tuples
Applied 3 strategies in 0.02 seconds
Graph statistics for `ecoinvent-3.12-biosphere` importer:
9850 graph nodes:
	emission: 9477
	natural resource: 353
	inventory indicator: 15
	economic: 5
0 graph edges:
0 edges to the following databases:
0 unique unlinked edges (0 total):

100%|██████████| 9850/9850 [00:00<00:00, 22741.50it/s]

14:35:53+0200 [info     ] Vacuuming database
Created database: ecoinvent-3.12-biosphere
Extracting XML data from 23191 datasets

100%|██████████| 23191/23191 [04:14<00:00, 91.10it/s]

14:40:11+0200 [info     ] Extracted 23191 datasets in 255.47 seconds
Applying strategy: normalize_units
Applying strategy: update_ecoinvent_locations
Applying strategy: remove_zero_amount_coproducts
Applying strategy: remove_zero_amount_inputs_with_no_activity
Applying strategy: remove_unnamed_parameters
Applying strategy: es2_assign_only_product_with_amount_as_reference_product
Applying strategy: assign_single_product_as_activity
Applying strategy: create_composite_code
Applying strategy: drop_unspecified_subcategories
Applying strategy: fix_ecoinvent_flows_pre35
Applying strategy: drop_temporary_outdated_biosphere_flows
Applying strategy: link_biosphere_by_flow_uuid
Applying strategy: link_internal_technosphere_by_composite_code
Applying strategy: delete_exchanges_missing_activity
Applying strategy: delete_ghost_exchanges
Applying strategy: remove_uncertainty_from_negative_loss_exchanges
Applying strategy: fix_unreasonably_high_lognormal_uncertainties
Applying strategy: convert_activity_parameters_to_list
Applying strategy: add_cpc_classification_from_single_reference_product
Applying strategy: delete_none_synonyms
Applying strategy: update_social_flows_in_older_consequential
Applying strategy: set_lognormal_loc_value
Applied 22 strategies in 8.48 seconds
Graph statistics for `ecoinvent-3.12-consequential` importer:
23191 graph nodes:
	process: 23191
726722 graph edges:
	biosphere: 434383
	technosphere: 269148
	production: 23191
726722 edges to the following databases:
	ecoinvent-3.12-biosphere: 434383
	ecoinvent-3.12-consequential: 292339
0 unique unlinked edges (0 total):


14:40:22+0200 [warning  ] Not able to determine geocollections for all datasets. This database is not ready for regionalization.

100%|██████████| 23191/23191 [00:34<00:00, 663.38it/s]

14:41:00+0200 [info     ] Vacuuming database
Created database: ecoinvent-3.12-consequential

## 3. Option B: install ecoinvent with Ecospold files

In [8]:
# Install the relevant biosphere database
biosphere_importer = Ecospold2BiosphereImporter(
    version = Config.ECOINVENT_VERSION,
    filepath = Config.ECOINVENT_BIOSPHERE_PATH,
    name = Config.ECOINVENT_BIOSPHERE_NAME
)

In [9]:
biosphere_importer.apply_strategies()

Applying strategy: normalize_units
Applying strategy: drop_unspecified_subcategories
Applying strategy: ensure_categories_are_tuples
Applied 3 strategies in 0.03 seconds

In [10]:
pd.DataFrame(biosphere_importer.unlinked)

Empty DataFrame
Columns: []
Index: []

In [11]:
biosphere_importer.write_database()

100%|██████████| 9850/9850 [00:00<00:00, 21792.19it/s]

15:42:40+0200 [info     ] Vacuuming database
Created database: ecoinvent-3.12-biosphere

Brightway2 SQLiteBackend: ecoinvent-3.12-biosphere

In [12]:
# Create importer
importer = bi.SingleOutputEcospold2Importer(
    Config.ECOINVENT_ECOSPOLD_PATH,
    Config.ECOINVENT_CLCA_NAME,
)

Extracting XML data from 23191 datasets

100%|██████████| 23191/23191 [05:53<00:00, 65.53it/s]

15:48:40+0200 [info     ] Extracted 23191 datasets in 354.51 seconds

In [13]:
# Apply import strategies
importer.apply_strategies()

Applying strategy: normalize_units
Applying strategy: update_ecoinvent_locations
Applying strategy: remove_zero_amount_coproducts
Applying strategy: remove_zero_amount_inputs_with_no_activity
Applying strategy: remove_unnamed_parameters
Applying strategy: es2_assign_only_product_with_amount_as_reference_product
Applying strategy: assign_single_product_as_activity
Applying strategy: create_composite_code
Applying strategy: drop_unspecified_subcategories
Applying strategy: fix_ecoinvent_flows_pre35
Applying strategy: drop_temporary_outdated_biosphere_flows
Applying strategy: link_biosphere_by_flow_uuid
Applying strategy: link_internal_technosphere_by_composite_code
Applying strategy: delete_exchanges_missing_activity
Applying strategy: delete_ghost_exchanges
Applying strategy: remove_uncertainty_from_negative_loss_exchanges
Applying strategy: fix_unreasonably_high_lognormal_uncertainties
Applying strategy: convert_activity_parameters_to_list
Applying strategy: add_cpc_classification_from_single_reference_product
Applying strategy: delete_none_synonyms
Applying strategy: update_social_flows_in_older_consequential
Applying strategy: set_lognormal_loc_value
Applied 22 strategies in 13.28 seconds

In [14]:
# Inspect unlinked exchanges
pd.DataFrame(importer.unlinked)

Empty DataFrame
Columns: []
Index: []

In [15]:
# If no unlinked exchanges are found, write the database to the Brightway project 
importer.write_database()

15:55:36+0200 [warning  ] Not able to determine geocollections for all datasets. This database is not ready for regionalization.

100%|██████████| 23191/23191 [01:09<00:00, 334.62it/s]

15:56:47+0200 [info     ] Vacuuming database
Created database: ecoinvent-3.12-consequential

Brightway2 SQLiteBackend: ecoinvent-3.12-consequential

In [19]:
# Verify that the database has been created
bd.databases

Databases dictionary with 2 object(s):
	ecoinvent-3.12-biosphere
	ecoinvent-3.12-consequential